#
#  ____    ____       ______        _____          ____        ______  _______    ____
# |    |  |    |  ___|\     \   ___|\    \    ____|\   \      |      \/       \  |    |_____      _____
# |    |  |    | |     \     \ |    |\    \  /    /\    \    /          /\     \ |    |\    \    /    /
# |    | /    // |     ,_____/||    | |    ||    |  |    |  /     /\   / /\     ||    | \    \  /    /
# |    |/ _ _//  |     \--'\_|/|    |/____/ |    |__|    | /     /\ \_/ / /    /||    |  \____\/____/
# |    |\    \'  |     /___/|  |    |\    \ |    .--.    ||     |  \|_|/ /    / ||    |  /    /\    \
# |    | \    \  |     \____|\ |    | |    ||    |  |    ||     |       |    |  ||    | /    /  \    \
# |____|  \____\ |____ '     /||____| |____||____|  |____||\____\       |____|  /|____|/____/ /\ \____\
# |    |   |    ||    /_____/ ||    | |    ||    |  |    || |    |      |    | / |    ||    |/  \|    |
# |____|   |____||____|     | /|____| |____||____|  |____| \|____|      |____|/  |____||____|    |____|
#   \(       )/    \( |_____|/   \(     )/    \(      )/      \(          )/       \(    \(        )/
#    '       '      '    )/       '     '      '      '        '          '         '     '        '
#                        '
#
settings:

  #
  # The messages settings. Remember that if you write "${text}" with "text" replaced with a key (section_key) in the config,
  # it will be replaced with its value. You can use this syntax also to put some special values written in the comments
  # over the key.
  #
  messages:

    #
    # The plugin's prefix
    #
    prefix: "&8[&dKeramix&8]"

    #
    # This message will be sent when a player flags a cheat.
    # The custom parameters are: ${flag-text}, ${flag-times} & ${player}
    #
    # Permission to see this message: keramix.flag.see
    #
    flagMessage: "${messages_prefix} &d${player} &8has failed &d${flag-name} &8[&d${flag-times}&8]"